baseURL = "https://www.literalarts.info/"
languageCode = "en"
theme = "kitab"
title = "Literal Arts"

disableKinds = ["taxonomy", "taxonomyTerm"]
pluralizelisttitles = false

[params]
  author = "tadanorik kurashita"
  description = "Literal Arts"
  dateFormat = "2006-01-02"
  footer1 = "知と遊び 道具を作り 世界を楽しむ"
  footer2 = " enjoy"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true