baseURL = "https://www.literalarts.info/"
languageCode = "en"
theme = "kitab"
title = "Literal Arts"

disableKinds = ["taxonomy", "taxonomyTerm"]
pluralizelisttitles = false

[params]
  author = "tadanorik kurashita"
  description = "Literal Arts"
  dateFormat = "2006-01-02"
  footer1 = "言葉と遊ぶ　言葉で遊ぶ"
  footer2 = "R-style"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true